export const emotionStates = [
  {
    id: 'calm',
    label: '平静',
    intent: '想安静下来',
    recommendationTags: ['助眠', '沉浸 0.8x', '轻音乐'],
    expression: {
      subtitle: '安静呼吸',
      aura: 'rgba(147, 197, 253,',
      motion: {
        beatMultiplier: 0.62,
        beatOffset: 0.04,
        response: 0.08,
        bounceHeight: 9,
        scaleX: 0.035,
        scaleY: 0.018,
        tiltScale: 4,
        idleSpeed: 1400,
        idleAmount: 0.025,
      },
    },
  },
  {
    id: 'happy',
    label: '快乐',
    intent: '想保持好心情',
    recommendationTags: ['快乐时光', 'KTV', '打游戏'],
    expression: {
      subtitle: '开心摇摆',
      aura: 'rgba(251, 191, 36,',
      motion: {
        beatMultiplier: 1,
        beatOffset: 0,
        response: 0.2,
        bounceHeight: 18,
        scaleX: 0.08,
        scaleY: 0.04,
        tiltScale: 12,
        idleSpeed: 700,
        idleAmount: 0.05,
      },
    },
  },
  {
    id: 'healing',
    label: '治愈',
    intent: '想被安抚',
    recommendationTags: ['轻音乐', '佛系时间', '正在旅行'],
    expression: {
      subtitle: '柔软陪伴',
      aura: 'rgba(52, 211, 153,',
      motion: {
        beatMultiplier: 0.78,
        beatOffset: 0.03,
        response: 0.12,
        bounceHeight: 12,
        scaleX: 0.05,
        scaleY: 0.025,
        tiltScale: 6,
        idleSpeed: 1100,
        idleAmount: 0.035,
      },
    },
  },
  {
    id: 'relaxed',
    label: '放松',
    intent: '想松弛休息',
    recommendationTags: ['Chill 放松', '海边', '雨天'],
    expression: {
      subtitle: '慢慢晃动',
      aura: 'rgba(34, 211, 238,',
      motion: {
        beatMultiplier: 0.72,
        beatOffset: 0.02,
        response: 0.1,
        bounceHeight: 10,
        scaleX: 0.045,
        scaleY: 0.02,
        tiltScale: 5,
        idleSpeed: 1200,
        idleAmount: 0.03,
      },
    },
  },
  {
    id: 'down',
    label: '低落',
    intent: '想承认情绪',
    recommendationTags: ['夜晚独处', '慢歌'],
    expression: {
      subtitle: '低低待着',
      aura: 'rgba(148, 163, 184,',
      motion: {
        beatMultiplier: 0.5,
        beatOffset: 0.02,
        response: 0.07,
        bounceHeight: 7,
        scaleX: 0.025,
        scaleY: 0.012,
        tiltScale: 3,
        idleSpeed: 1600,
        idleAmount: 0.02,
      },
    },
  },
  {
    id: 'emo',
    label: 'EMO',
    intent: '想沉浸情绪',
    recommendationTags: ['深夜 EMO', '失恋必听'],
    expression: {
      subtitle: '慢速共振',
      aura: 'rgba(129, 140, 248,',
      motion: {
        beatMultiplier: 0.56,
        beatOffset: 0.04,
        response: 0.08,
        bounceHeight: 11,
        scaleX: 0.04,
        scaleY: 0.02,
        tiltScale: 5,
        idleSpeed: 1200,
        idleAmount: 0.025,
      },
    },
  },
  {
    id: 'romantic',
    label: '浪漫',
    intent: '想进入亲密氛围',
    recommendationTags: ['浪漫情歌', '小酒馆', 'R&B'],
    expression: {
      subtitle: '微光心动',
      aura: 'rgba(244, 114, 182,',
      motion: {
        beatMultiplier: 0.82,
        beatOffset: 0.03,
        response: 0.13,
        bounceHeight: 13,
        scaleX: 0.055,
        scaleY: 0.025,
        tiltScale: 7,
        idleSpeed: 980,
        idleAmount: 0.04,
      },
    },
  },
  {
    id: 'nostalgic',
    label: '怀旧',
    intent: '想回到旧时刻',
    recommendationTags: ['怀旧老歌', '经典', '古典'],
    expression: {
      subtitle: '复古摆动',
      aura: 'rgba(251, 146, 60,',
      motion: {
        beatMultiplier: 0.68,
        beatOffset: 0.03,
        response: 0.1,
        bounceHeight: 10,
        scaleX: 0.04,
        scaleY: 0.02,
        tiltScale: 5,
        idleSpeed: 1320,
        idleAmount: 0.028,
      },
    },
  },
  {
    id: 'energetic',
    label: '元气',
    intent: '想被唤醒',
    recommendationTags: ['起床', '健身', '通勤/驾驶'],
    expression: {
      subtitle: '高能弹跳',
      aura: 'rgba(45, 212, 191,',
      motion: {
        beatMultiplier: 1.12,
        beatOffset: 0,
        response: 0.24,
        bounceHeight: 20,
        scaleX: 0.1,
        scaleY: 0.055,
        tiltScale: 14,
        idleSpeed: 620,
        idleAmount: 0.06,
      },
    },
  },
  {
    id: 'focused',
    label: '专注',
    intent: '想稳定注意力',
    recommendationTags: ['专注模式', '阅读/工作'],
    expression: {
      subtitle: '稳定律动',
      aura: 'rgba(96, 165, 250,',
      motion: {
        beatMultiplier: 0.58,
        beatOffset: 0.03,
        response: 0.06,
        bounceHeight: 8,
        scaleX: 0.025,
        scaleY: 0.012,
        tiltScale: 3,
        idleSpeed: 1800,
        idleAmount: 0.018,
      },
    },
  },
  {
    id: 'lonely',
    label: '孤独',
    intent: '想独处',
    recommendationTags: ['夜晚', '深夜', '失恋'],
    expression: {
      subtitle: '静静相伴',
      aura: 'rgba(165, 180, 252,',
      motion: {
        beatMultiplier: 0.48,
        beatOffset: 0.03,
        response: 0.06,
        bounceHeight: 7,
        scaleX: 0.022,
        scaleY: 0.012,
        tiltScale: 3,
        idleSpeed: 1700,
        idleAmount: 0.02,
      },
    },
  },
  {
    id: 'lucky',
    label: '幸运',
    intent: '想获得积极暗示',
    recommendationTags: ['好运'],
    expression: {
      subtitle: '闪闪好运',
      aura: 'rgba(250, 204, 21,',
      motion: {
        beatMultiplier: 0.92,
        beatOffset: 0.04,
        response: 0.16,
        bounceHeight: 16,
        scaleX: 0.065,
        scaleY: 0.03,
        tiltScale: 9,
        idleSpeed: 820,
        idleAmount: 0.045,
      },
    },
  },
];

export const defaultEmotionId = 'happy';

export const getEmotionById = (emotionId) => (
  emotionStates.find((emotion) => emotion.id === emotionId) ?? emotionStates[0]
);

